# fly.toml app configuration file generated for notifications-jordanreger on 2024-04-29T17:27:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notifications-jordanreger'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
